### ISSUE TITLE
Compatibility with WIO Terminal

### ISSUE THREAD

**Issue by Dev-byte-source** [tesa-klebeband/RTL8720dn-Deauther#4] opened 2024-09-17 15:42 UTC
Hi,

Seeed Stuidio's WIO terminal as well uses the same RTL8720DN. 
I am trying to run run this code on WIO terminal. I am noob and not able to do so.

Using Arduino IDE, when compiled for AI-Thinker BW16(RTL8720DN) code compiles successfully but it does not upload to WIO terminal.
Similarly, given code can not be compiled when board is set to WIO terminal. Please suggest me how to proceed from here.

**Comment by tesa-klebeband** [comment] 2024-09-17 15:59
Hi,
You probably should choose the wio terminal device when you compile the code. Could you please give me the error log, so I can try to help you get it working?

**Comment by Dev-byte-source** [comment] 2024-09-30 21:48
I am sorry for delayed response. I had to travel
[RTL8720dn-Deauther-master-Dev-Byte_Source.zip](https://github.com/user-attachments/files/17196746/RTL8720dn-Deauther-master-Dev-Byte_Source.zip)
 without laptop.

In order to resolve the errors, I have commented the header files which IDE is not able to find for WIO terminal. I have attached source code that I am using to this as well.

I'm getting following errors:
```
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp: In function 'void wifi_tx_raw_frame(void*, size_t)':
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp:12:48: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
   void *frame_control = alloc_mgtxmitframe(ptr + 0xae0);
                                            ~~~~^~~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp:15:48: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
     update_mgntframe_attrib(ptr, frame_control + 8);
                                  ~~~~~~~~~~~~~~^~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp:16:48: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
     memset((void *)*(uint32_t *)(frame_control + 0x80), 0, 0x68);
                                  ~~~~~~~~~~~~~~^~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp:17:66: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
     uint8_t *frame_data = (uint8_t *)*(uint32_t *)(frame_control + 0x80) + 0x28;
                                                    ~~~~~~~~~~~~~~^~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp:19:33: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
     *(uint32_t *)(frame_control + 0x14) = length;
                   ~~~~~~~~~~~~~~^~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\wifi_cust_tx.cpp:20:33: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
     *(uint32_t *)(frame_control + 0x18) = length;
                   ~~~~~~~~~~~~~~^~~~~~
In file included from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/arch.h:49:0,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/debug.h:40,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/opt.h:52,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/ip_addr.h:40,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/tcpip_adapter.h:44,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/esp_event.h:25,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/esp_event_loop.h:22,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/esp_lib_unified.h:12,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/seeed_rpcUnified.h:11,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/WiFiGeneric.h:26,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/WiFiSTA.h:28,
                 from c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/WiFi.h:32,
                 from D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:8:
c:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/arch/cc.h:44:0: warning: "BYTE_ORDER" redefined
 #define BYTE_ORDER LITTLE_ENDIAN
 
In file included from c:\users\admin\appdata\local\arduino15\packages\seeeduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\sys\types.h:67:0,
                 from c:\users\admin\appdata\local\arduino15\packages\seeeduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\stdio.h:61,
                 from C:\Users\Admin\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.5\cores\arduino/Print.h:23,
                 from C:\Users\Admin\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.5\cores\arduino/Stream.h:26,
                 from C:\Users\Admin\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.5\cores\arduino/HardwareSerial.h:24,
                 from C:\Users\Admin\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.5\cores\arduino/Arduino.h:83,
                 from C:\Users\Admin\AppData\Local\Temp\arduino\sketches\A1CD291A1EF4DD0E4CF9F684FB1E221D\sketch\RTL8720dn-Deauther.ino.cpp:1:
c:\users\admin\appdata\local\arduino15\packages\seeeduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\machine\endian.h:20:0: note: this is the location of the previous definition
 #define BYTE_ORDER _BYTE_ORDER
 
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:25:14: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *ssid = "RTL8720dn-Deauther";
              ^~~~~~~~~~~~~~~~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:26:14: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *pass = "0123456789";
              ^~~~~~~~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino: In function 'void handleRoot(WiFiClient&)':
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:130:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < scan_results.size(); i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino: In function 'void startDeauth(int)':
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:185:8: error: 'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?
   WiFi.apbegin(ssid, pass, (char *) String(current_channel).c_str());
        ^~~~~~~
        begin
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino: In function 'void setup()':
D:\Arduino code\wifi\RTL8720dn-Deauther-master\RTL8720dn-Deauther-master\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:199:8: error: 'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?
   WiFi.apbegin(ssid, pass, (char *) String(current_channel).c_str());
        ^~~~~~~
        begin
Multiple libraries were found for "FreeRTOS.h"
  Used: C:\Users\Admin\Documents\Arduino\libraries\Seeed_Arduino_FreeRTOS
  Not used: C:\Users\Admin\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.5\libraries\Seeed_Arduino_FreeRTOS
exit status 1

Compilation error: 'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?
```

**Comment by tesa-klebeband** [comment] 2024-10-01 07:10
Hmm that's weird. It looks like the problem is with the seedstudio WiFi libraries and not with my code. Could you try to create the access point (where currently apbegin is in use) by using the functions from the seedstudio libraries (examples can usually be found online or in the examples tab in the ide). It could also be that you don't have the right board selected.

**Comment by Dev-byte-source** [comment] 2024-10-02 20:32
> Hmm that's weird. It looks like the problem is with the seedstudio WiFi libraries and not with my code. Could you try to create the access point (where currently apbegin is in use) by using the functions from the seedstudio libraries (examples can usually be found online or in the examples tab in the ide). It could also be that you don't have the right board selected.

Regarding the right board selection, I am able to run some sample codes with same settings. 
Let me try creating AP with their examples. and get back to you. This might take some days depending on my current commitments. I'll update here once I have done that.

**Comment by tesa-klebeband** [comment] 2024-10-03 07:22
Sounds good! Let me know how it goes

**Comment by tesa-klebeband** [comment] 2024-10-28 14:42
I'm going to close this issue for now. If you guys figure out something new, feel free to just reopen it.

**Closed by tesa-klebeband** 2024-10-28 14:42 UTC
